### ISSUE TITLE
Creating .gitignore global file.

### ISSUE THREAD

**Issue by venikman** [sholladay/todo#1]
Let’s create guide for global .girignore file and also translate it to russian. You could also learn russian from it.

**Comment by sholladay** [comment]
I have broken this up into three issues and put the ones related to guides in the relevant repository.

 - Guide for global vs local gitignore files: https://github.com/sholladay/guides/issues/1
 - Localize guides: https://github.com/sholladay/guides/issues/2
 - Learn Russian: sholladay/todo#2
